config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView, TemplateView

from termplanner.terms.views import HomeView

admin.site.site_header = "VAWi Planer Administration"
admin.site.index_title = "Planer Verwaltung"

urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "imprint/",
        TemplateView.as_view(template_name="pages/imprint.html"),
        name="imprint",
    ),
    path(
        "privacy/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("termplanner.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "favicon.ico/",
        RedirectView.as_view(url=f"{settings.STATIC_URL}images/favicons/favicon.ico"),
    ),
    path("semester/", include("termplanner.terms.urls", namespace="terms")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

termplanner/terms/urls.py
from django.urls import path

from . import views

app_name = "terms"
urlpatterns = [
    # Semestermodule paths
    path(route="", view=views.SemesterModuleListView.as_view(), name="list"),
    path(route="add/", view=views.SemesterModuleCreateView.as_view(), name="add"),
    path(
        route="<int:pk>/update/",
        view=views.SemesterModuleUpdateView.as_view(),
        name="update",
    ),
    path(
        route="<int:pk>/", view=views.SemesterModuleDetailView.as_view(), name="detail"
    ),
    path(
        route="<int:pk>/delete/",
        view=views.SemesterModuleDeleteView.as_view(),
        name="delete",
    ),
    # Events paths
    path(
        route="<int:semestermodule_id>/event/<int:pk>",
        view=views.EventDetailView.as_view(),
        name="detail_event",
    ),
    path(
        route="event/<int:pk>/update/",
        view=views.EventUpdateView.as_view(),
        name="update_event",
    ),
    path(
        route="<int:semestermodule_id>/event/add/",
        view=views.EventCreateView.as_view(),
        name="add_event",
    ),
    path(
        route="<int:semestermodule_id>/event/<int:pk>/delete",
        view=views.EventDeleteView.as_view(),
        name="delete_event",
    ),
    path(route="ajax/load-modules/", view=views.load_modules, name="ajax_load_modules"),
    path(
        route="events_pdf", view=views.events_semestermodule_pdf_view, name="events_pdf"
    ),
]

termplanner/users/urls.py
from django.urls import path

from termplanner.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

termplanner/terms/models.py
import datetime
from datetime import timedelta

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel


class Module(TimeStampedModel):
    title = models.CharField("Titel des Moduls", max_length=255)
    short_title = models.CharField("Abkürzung des Moduls", max_length=5)
    description = models.TextField("Beschreibung zum Modul")
    host = models.CharField("Anbieter des Moduls", max_length=255)
    quota_economics = models.IntegerField("Anteil Wirtschaftswissenschaft", default=0)
    quota_cs = models.IntegerField("Anteil Informatik", default=0)
    quota_is = models.IntegerField("Anteil Wirtschaftsinformatik", default=0)
    quota_key_competence = models.IntegerField("Anteil Schlüsselkompetenz", default=0)
    ects = models.IntegerField("ECTS Punkte", default=0)
    TermType = models.TextChoices("TermType", "SS WS SS/WS")
    term = models.CharField(choices=TermType.choices, max_length=5, default=TermType.SS)

    class Meta:
        verbose_name_plural = "Module"
        verbose_name = "Modul"

    def __str__(self):
        return self.title


class TermStarts(datetime.date, models.Choices):
    WS_18 = 2018, 10, 1, "Wintersemester 2018/19"
    SS_19 = 2019, 4, 1, "Sommersemester 2019"
    WS_19 = 2019, 10, 1, "Wintersemester 2019/20"
    SS_20 = 2020, 4, 1, "Sommersemester 2020"
    WS_20 = 2020, 10, 1, "Wintersemester 2020/21"
    SS_21 = 2021, 4, 1, "Sommersemester 2021"
    WS_21 = 2021, 10, 1, "Wintersemester 2021/22"


class SemesterModule(TimeStampedModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="semester_modules",
    )
    module = models.ForeignKey(
        Module,
        verbose_name="Modulbezeichnung",
        on_delete=models.SET_NULL,
        null=True,
        related_name="semester_modules",
    )
    term = models.DateField(choices=TermStarts.choices, verbose_name="Semester")
    points_sl = models.FloatField(
        "Punkte Studienleistung",
        validators=[MinValueValidator(0.0), MaxValueValidator(18)],
        null=True,
        blank=True,
    )
    points_exam = models.FloatField(
        "Punkte Klausur",
        validators=[MinValueValidator(0.0), MaxValueValidator(90)],
        null=True,
        blank=True,
    )
    grade = models.FloatField(
        "Note",
        validators=[MinValueValidator(1.0), MaxValueValidator(5.0)],
        null=True,
        blank=True,
    )
    done = models.BooleanField("Erledigt?", default=False)

    @property
    def last_three_events(self):
        return Event.open_objects.filter(semestermodule=self.pk)[:3]

    class Meta:
        ordering = ["term"]

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        """Return absolute url to the semestermodule detail page."""
        return reverse("terms:detail", kwargs={"pk": self.pk})


class OpenEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(done=False)


class Event(TimeStampedModel):
    class EventType(models.TextChoices):
        SCRIPT = "SC", _("Skriptbearbeitung")
        SL = "SL", _("Studienleistung")
        EXAM_A = "EA", _("Klausur Block A")
        EXAM_B = "EB", _("Klausur Block B")
        EXAM_C = "EC", _("Klausur Block C")
        TERM_PAPER = "TP", _("Hausarbeit")
        ALIGNMENT = "AL", _("Abstimmungstermin")

    semestermodule = models.ForeignKey(
        SemesterModule, on_delete=models.CASCADE, related_name="events"
    )
    title = models.CharField("Bezeichnung", max_length=255)
    start_date = models.DateTimeField("Start des Ereignisses")
    end_date = models.DateTimeField("Ende des Ereignisses", blank=True, null=True)
    event_type = models.CharField(
        "Art des Ereignisses",
        max_length=2,
        choices=EventType.choices,
        default=EventType.SCRIPT,
    )
    note = models.TextField("Notiz", blank=True)
    done = models.BooleanField("Erledigt?", default=False)
    done_at = models.DateTimeField("Erledigt am", blank=True, null=True)

    @property
    def all_day(self):
        if self.end_date:
            delta = self.end_date - self.start_date
            if delta.days > 0 or delta.days < 0:
                return True
        else:
            return False

    @property
    def day_after_end(self):
        if self.end_date:
            return self.end_date + timedelta(days=1)

    objects = models.Manager()
    open_objects = OpenEventManager()

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Return absolute url to the events detail page."""
        return reverse(
            "terms:detail_event",
            kwargs={"pk": self.pk, "semestermodule_id": self.semestermodule_id},
        )

termplanner/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Termplanner."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

termplanner/terms/forms.py
from django import forms
from tempus_dominus.widgets import DateTimePicker

from .models import Event, Module, SemesterModule


class SemesterModuleForm(forms.ModelForm):
    class Meta:
        model = SemesterModule
        fields = ("term", "module", "points_sl", "points_exam", "grade", "done")
        help_texts = {"module": "Bitte Semester zuerst auswählen"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["module"].queryset = Module.objects.none()

        if "term" in self.data:
            try:
                # get the selected modules primary key
                module_pk = self.data.get("module")
                # grab information from the db of that module
                module = Module.objects.get(pk=module_pk)
                # get the term of the module
                term = module.term
                self.fields["module"].queryset = Module.objects.filter(
                    term=term
                ).order_by("title")
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields["module"].queryset = Module.objects.filter(
                term=self.instance.module.term
            ).order_by("title")


class EventForm(forms.ModelForm):
    title = forms.CharField(label="Titel")
    note = forms.CharField(widget=forms.Textarea, label="Notiz", required=False)
    start_date = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                "useCurrent": True,
                "collapse": True,
                "format": "DD.MM.YYYY HH:mm",
            },
            attrs={
                "append": "fa fa-calendar",
                "icon_toggle": True,
            },
        ),
        label="Startzeitpunkt",
    )
    end_date = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                "useCurrent": True,
                "collapse": True,
                "format": "DD.MM.YYYY HH:mm",
            },
            attrs={
                "append": "fa fa-calendar",
                "icon_toggle": True,
            },
        ),
        label="Endezeitpunkt",
        required=False,
    )
    done = forms.BooleanField(label="Erledigt?", required=False)
    event_type = forms.ChoiceField(
        label="Art des Ereignisses", choices=Event.EventType.choices
    )

    class Meta:
        model = Event
        fields = ["title", "note", "start_date", "end_date", "done", "event_type"]

termplanner/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

termplanner/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("terms:list")


user_redirect_view = UserRedirectView.as_view()

termplanner/templates/terms/event_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <p>Bist du sicher, dass du den Termin {{ event.title }} löschen willst?</p>
    <input class="btn btn-danger" type="submit" value="Löschen bestätigen" />
  </form>

{% endblock %}

termplanner/templates/terms/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col"><h1>{{ event.title }}</h1></div>
      <div class="col">
        <a class="float-right btn btn-danger" role="button" href="{% url "terms:delete_event" event.semestermodule.id event.id %}">Termin löschen</a>
        <a class="float-right btn btn-secondary mr-2" role="button" href="{% url "terms:update_event" event.id %}">Termin ändern</a>
      </div>
    </div>
    <table class="table">
      <tr>
        <td>Modul</td>
        <td>{{ event.semestermodule.module.title}}</td>
      </tr>
      <tr>
        <td>Semester</td>
        <td>{{ event.semestermodule.get_term_display }}</td>
      </tr>
      <tr>
        <td>Typ</td>
        <td>{{ event.get_event_type_display }}</td>
      </tr>
      <tr>
        <td>Start</td>
        <td>{{ event.start_date }}</td>
      </tr>
      <tr>
        <td>Ende</td>
        <td>
          {% if event.end_date %}
            {{ event.end_date }}
          {% else %}
            -
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>Erledigt?</td>
        {% if event.done == True %}
          <td>
          <svg class="bi text-success" width="25" height="25" fill="currentColor">
            <use xlink:href="{% static 'images/bootstrap-icons.svg' %}#check-circle"/>
          </svg>
          </td>

        {% else %}
          <td>
          <svg class="bi text-danger" width="25" height="25" fill="currentColor">
            <use xlink:href="{% static 'images/bootstrap-icons.svg' %}#x-circle"/>
          </svg>
          </td>
        {% endif %}
      </tr>
    </table>
    <h2>Notiz zum Ereignis</h2>
    {% if event.note %}
      <p>{{ event.note }}</p>
    {% else %}
      <p>Es wurden noch keine Notizen hinterlegt.</p>
    {% endif %}
    <p>
      <a class="float-right btn btn-info" role="button" href="{% url 'terms:list'%}">zurück zum Dashboard</a>
      <a class="float-right btn btn-info mr-2" role="button" href="{% url 'terms:detail' event.semestermodule.id %}">zurück zum Modul</a>
    </p>
  </div>
{% endblock content %}

termplanner/templates/terms/event_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
{% endblock css %}
{% block javascript %}
    {{ block.super }}
    {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
    {{ form.media }}
{% endblock javascript %}

{% block title %}
  Ereignis zu Modul hinzufügen
{% endblock title %}

{% block content %}
  {% if view.action == "Update" %}
    <h1>Ereignis bearbeiten</h1>
  {% else %}
    <h1>Ereignis zu Modul hinzufügen</h1>
  {% endif %}
  <form action="." method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Speichern</button>
  {% if view.action == "Update" %}
    <a class="btn btn-danger" role="button" href="{% url "terms:delete_event" event.semestermodule.id event.id %}">Termin löschen</a>
  {% endif %}
  </form>
{% endblock content %}

termplanner/templates/terms/event_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

termplanner/templates/terms/semestermodule_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <p>Bist du sicher, dass du das Modul {{ event.title }} löschen willst?</p>
    <input class="btn btn-danger" type="submit" value="Löschen bestätigen" />
  </form>
{% endblock %}

termplanner/templates/terms/semestermodule_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h2>{{ semestermodule.module.title }}</h2>
      </div>
      <div class="col-6">
        <a class="btn btn-danger float-right mr-0" role="button" href="{% url "terms:delete" semestermodule.id %}">Modul löschen</a>
        <a class="btn btn-secondary float-right mr-2" role="button" href="{% url "terms:update" semestermodule.id %}">Modul ändern</a>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col">
        {% if days_until_exam_a %}
          <p>Es sind noch {{ days_until_exam_a }} Tage bis zur Klausur in Block A.</p>
        {% endif %}
        {% if days_until_exam_b %}
          {% if days_until_exam_a == None %}
            <p>Es sind noch {{ days_until_exam_b }} Tage bis zur Klausur in Block B.</p>
          {% endif %}
        {% endif %}
      </div>
    </div>


    <div class="row mt-3 mb-2">
      <div class="col-6">
        <h3>Termine</h3>
      </div>
      <div class="col-6">
        <a class="btn btn-secondary float-right" role="button" href="{% url "terms:add_event" semestermodule.id%}">
          Termin hinzufügen
        </a>
      </div>
    </div>
    {% if event_list %}
      <table class="table">
      <thead class="table_vawi">
        <tr>
          <th scope="col">Startdatum</th>
          <th scope="col">Enddatum</th>
          <th scope="col">Art</th>
          <th scope="col">Bezeichnung</th>
          <th scope="col">Erledigt?</th>
          <th scope="col">Aktion</th>
        </tr>
      </thead>
      <tbody>
        {% for event in event_list %}
          <tr>
            <td>
              {{ event.start_date|date:"SHORT_DATE_FORMAT" }}
            </td>
            <td>
              {% if event.end_date %}
                {{ event.end_date|date:"SHORT_DATE_FORMAT" }}
              {% else %}
                -
              {% endif %}
            </td>
            <td>
              {{ event.get_event_type_display }}
            </td>
            <td>
              <a href="{% url 'terms:detail_event' semestermodule.id event.id %}">{{ event.title }}</a>
            </td>
            {% if event.done == True %}
              <td>
              <svg class="bi text-success" width="25" height="25" fill="currentColor">
                <use xlink:href="{% static 'images/bootstrap-icons.svg' %}#check-circle"/>
              </svg>
              </td>
            {% else %}
              <td>
              <svg class="bi text-danger" width="25" height="25" fill="currentColor">
                <use xlink:href="{% static 'images/bootstrap-icons.svg' %}#x-circle"/>
              </svg>
              </td>
            {% endif %}
            <td>
              <a href="{% url 'terms:update_event' event.id %}">Bearbeiten</a>
            </td>
          </tr>

      {% endfor %}
      </tbody>

    </table>
    {% else %}
      <div class="row">
        <div class="col">
          <p>Es wurden noch keine Termine für das Modul erfasst.</p>
        </div>
      </div>

    {% endif %}


    <div class="row mt-4">
      <div class="col">
        <h5>Belegt im {{ semestermodule.get_term_display }}</h5>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <table class="table">
          <tr>
            <td>Punkte Studienleistung</td>
            <td>
              {% if semestermodule.points_sl %}
                {{ semestermodule.points_sl }}
              {% else %}
                -
              {% endif %}
            </td>
          </tr>
          <tr>
            <td>Punkte Klausur</td>
            <td>
              {% if semestermodule.points_exam %}
                {{ semestermodule.points_exam }}
              {% else %}
                -
              {% endif %}
            </td>
          </tr>
          <tr>
            <td>Note</td>
            <td>
              {% if semestermodule.grade %}
                {{ semestermodule.grade }}
              {% else %}
                -
              {% endif %}
            </td>
          </tr>
        </table>
      </div>
    </div>


    <h2 class="mt-4">Angaben zum Modul</h2>
    <table class="table">
      <tr>
        <td>Anbieter</td>
        <td>{{ semestermodule.module.host }}</td>
      </tr>
      <tr>
        <td>Beschreibung</td>
        <td>{{ semestermodule.module.description|linebreaks }}</td>
      </tr>
      <tr>
        <td>ECTS</td>
        <td>{{ semestermodule.module.ects }}</td>
      </tr>
      <tr>
        <td>Anteil WiWi</td>
        <td>{{ semestermodule.module.quota_economics }}</td>
      </tr>
      <tr>
        <td>Anteil Informatik</td>
        <td>{{ semestermodule.module.quota_cs }}</td>
      </tr>
      <tr>
        <td>Anteil Wirtschaftsinformatik</td>
        <td>{{ semestermodule.module.quota_is }}</td>
      </tr>
      <tr>
        <td>Anteil Schlüsselkompetenzen</td>
        <td>{{ semestermodule.module.quota_key_competence }}</td>
      </tr>
    </table>
  </div>


{% endblock content %}

termplanner/templates/terms/semestermodule_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Modul hinzufügen
{% endblock title %}

{% block content %}
  <h1>Modul hinzufügen</h1>
  <form action="." method="post" id="semesterModuleForm" data-modules-url="{% url 'terms:ajax_load_modules' %}">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Speichern</button>
  </form>

{% endblock content %}
{% block custom_javascript %}
  <script>

    $("#id_term").change(function() {
      let url = $("#semesterModuleForm").attr("data-modules-url");
      let term = $("#id_term option:selected").text();
      if (term.indexOf("Winter") >= 0) {
        term = "WS"
      } else {
        term = "SS"
      }

      $.ajax({
        url: url,
        data: {
          'term': term
        },
        success: function (data) {
          $("#id_module").html(data);
        }
      });

    });

  </script>
{% endblock %}